version: '3.8'

services:
  qgis:
    build: .
    image: qgis/qgis-custom
    volumes:
      - ./data:/home/qgis/data
      - ./config:/home/qgis/config
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    environment:
      - QGIS_PROJECT_PATH=/home/qgis/data
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
    ports:
      - "8080:80"
    command: ["qgis"]

volumes:
  data:
  config: